name: Test
on:
  workflow_dispatch

jobs:
  lint-crls:
    runs-on: ubuntu-latest
    steps:
    # Checkout this repo:
    - uses: actions/checkout@v3
    # Python:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - run: pip install pipx
    - run: pipx install pkilint
    - run: mkdir CRLs
    - run: curl -sSZ 'http://stg.c.lencr.org/{4169287449788112,58367272336442518}/[0-127].crl' -o 'CRLs/stg_#1_#2.crl'
    - run: curl -sSZ 'http://prod.c.lencr.org/{20506757847264211,67430855296768143}/[0-127].crl' -o 'CRLs/prod_#1_#2.crl'
    - name: lint_crl on all CRLs
      run: |
        for CRL in CRLs/*; do
          echo "$CRL:"
          openssl crl -inform DER -noout -crlnumber -lastupdate -issuer < "$CRL"
          echo "Lint results:"
          lint_crl lint -t CRL -p BR "$CRL"
        done

